rm -rf ${pipedir}/kraken_standard
rm -rf ${pipedir}/blastdb
rm -rf ${pipedir}/singularities
rm -rf ${pipedir}/busco_downloads
rm -rf ${pipedir}/autogenerated_workflow.png
rm -rf ${pipedir}/workflow.png
rm -rf ${pipedir}/README.md
